apiVersion: ENC[AES256_GCM,data:HUY=,iv:r3U5VR79mPrVcChojmF+JsLAy2DwayIPHyLC8pTy1jg=,tag:tMqF3a8818Gu9sMK4abxPg==,type:str]
kind: ENC[AES256_GCM,data:5rXQPuVV,iv:Iv/+s05Jqnk+xgIP/EHA50Eb+lp+ixxTbU2FLMvCsE8=,tag:y6yWx6jXkbVpJNPCyCU5iA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zMWgGkGB5sQe6P5b,iv:BVpypKGuKXD1NcfHRil7+X2/LtX0vjGLn3YhdSotE5o=,tag:r32ZS1huadirfXC/Gy5z2Q==,type:str]
    namespace: ENC[AES256_GCM,data:FSmjjmZuA7yM,iv:J7FMFEB2ma5JFtPwj7Bp3wubaaInZodf2f6/bMeqPXo=,tag:Lqvm4PPgvhJBUCguHVGm6g==,type:str]
type: ENC[AES256_GCM,data:DJFwQjxf,iv:o+Vj8QmKrnlumTO15ubs0leyFhE1QWH1YRAZNb9y3b4=,tag:KjQ13FjnZ/s0y7cFutpa9A==,type:str]
stringData:
    mysql-root-password: ENC[AES256_GCM,data:rSgJNOCJjIhoVAIGLKZDsA==,iv:+0ZbkYhbg0JLDh8rGnrL81ugK2k+cHYTa81wZvvm9zI=,tag:r1E5ncthlUsBhPaeHUoL3w==,type:str]
    mysql-password: ENC[AES256_GCM,data:FvJqusTMKk3+aO33fLOKiA==,iv:YDMV34CQOM2ZPqssLu8hAFg7zlu+f2ROLc81tUDoEFI=,tag:U7xm2GeDvyigPSONbWLhPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hj5exu845fk9hgtewkhpg2xwm3vzqdnn5anj2gsv7szjq4tspgqp5mqwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNnBlci9mSGZNeE04czBE
            VS9ZRldHaHRCWVZPdnUzN25sdmJoRFRaaG40Ck5aTEVLb0lBRnJEa0JCZitLMXNN
            RXNqVjhHUFl1STd4LzRvWWZxRkZ1WEEKLS0tIHhwNjBlME5KWSsrS1JjV1U3VHpC
            VmZ5aG41TGlJTHJ2NnEwRmFMS1lXcFkKH/VKqGy3F1E7EcAcJ6X+b6yL1MYhIC7y
            hPdInqexhGOXSPRI8q+kDT+jhQorgKwOsuDkU4XbkFQXrU7ZiI8dbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T16:03:27Z"
    mac: ENC[AES256_GCM,data:uJkQLXVwG7X9YpLNQxInOA0ACETXiIStDPLblbo5e4DFizeJqZZiTQk/z/ur9TuLE9Z751OeCGwxzWdNRD2LfSQhk4YAUzdsTrdgJQ1dSUuLyij7bEgIG/fxqfSmdeCv7u0879x0mKDS5AzTiDR9acF/tcOpdZuanMKOgkO9Nw0=,iv:y3WyEdGkyNAAj8TJutNNC99o08i4mGSah9fJ8Gj7z9Y=,tag:nXUK9GtBHPkeX3fKNb2ZTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
