---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: mysql
      version: 9.11.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: mysql-secret
    primary:
      persistence:
        enabled: false
